name: Down Detector
description: Detect if a website is down
author: Kadir Gün
icon: alert-octagon
color: red

inputs:
  url:
    description: The URL to check
    required: true
  expected-status-codes:
    description: The expected status codes
    required: false
    default: 200
  expected-response-time:
    description: The expected response time in milliseconds
    required: false
    default: 3000
  discord-webhook:
    description: The Discord webhook URL
    required: false

outputs:
  response-time:
    description: The response time in milliseconds of the request
  status-code:
    description: The status code of the response

runs:
  using: node20
  main: dist/index.js
