name: Test Action

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to ping'
        required: true
        default: 'https://www.google.com'
      expected-status-codes:
        description: 'Expected status codes'
        required: true
        default: '200,201'
      discord-webhook:
        description: 'Discord Webhook URL'
        required: true

permissions:
  actions: read
  contents: read

jobs:
  say-hello:
    name: Detect Down
    runs-on: ubuntu-latest

    steps:
      - name: Ping URL
        id: ping
        uses: kadirgun/downdetect@main
        with:
          url: ${{ github.event.inputs.url }}
          expected-status-codes:
            ${{ github.event.inputs.expected-status-codes }}
          discord-webhook: ${{ github.event.inputs.discord-webhook }}
